# -*- coding: utf-8 -*-
"""TraceMyTarget

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14T3VumMapIZW4mNtYl1c-2oWQOblR_xq
"""

!pip install python-whois requests beautifulsoup4 ipwhois email_validator

# =============================
# IMPORTS
# =============================
import whois
import requests
from ipwhois import IPWhois
from email_validator import validate_email, EmailNotValidError
from datetime import datetime, timezone
import dateutil.parser
import socket

# =============================
# CONSTANTS
# =============================
HIGH_RISK_COUNTRIES = ["RU", "CN", "IR", "KP"]
HIBP_API_KEY = "YOUR_API_KEY_HERE"  # Ganti dengan API Key HIBP-mu
HIBP_HEADERS = {"hibp-api-key": HIBP_API_KEY, "user-agent": "OSINT-Agent"}

# =============================
# INPUT TYPE DETECTION
# =============================
def detect_input_type(input_str):
    try:
        validate_email(input_str)
        return "email"
    except EmailNotValidError:
        pass
    if "." in input_str:
        return "domain"
    return "username"

# =============================
# DATA COLLECTION
# =============================
def get_whois(domain):
    try:
        w = whois.whois(domain)
        return {
            "Domain": w.domain_name,
            "Registrar": w.registrar,
            "Creation Date": w.creation_date,
            "Expiration Date": w.expiration_date,
            "Name Servers": w.name_servers
        }
    except Exception as e:
        return {"Error": str(e)}

def get_ip_info(domain):
    try:
        ip = socket.gethostbyname(domain)
        obj = IPWhois(ip)
        res = obj.lookup_rdap()
        return {
            "IP": ip,
            "ASN": res.get("asn"),
            "Country": res.get("network", {}).get("country")
        }
    except Exception as e:
        return {"Error": str(e)}

def get_github_info_api(username):
    url = f"https://api.github.com/users/{username}/repos"
    try:
        r = requests.get(url, timeout=10)
        if r.status_code != 200:
            return {"Error": "User not found"}
        repos = [repo["name"] for repo in r.json()]
        return {"Username": username, "Repositories": repos}
    except Exception as e:
        return {"Error": str(e)}

# =============================
# EMAIL BREACH CHECK
# =============================
def check_email_breach(email):
    url = f"https://haveibeenpwned.com/api/v3/breachedaccount/{email}"
    try:
        r = requests.get(url, headers=HIBP_HEADERS, timeout=10)
        if r.status_code == 404:
            return {"Breached": False, "Breaches": []}
        elif r.status_code == 200:
            breaches = [b["Name"] for b in r.json()]
            return {"Breached": True, "Breaches": breaches}
        else:
            return {"Error": f"API response code {r.status_code}"}
    except Exception as e:
        return {"Error": str(e)}

# =============================
# ANALYSIS / FINDINGS
# =============================
def generate_findings(result):
    findings = []

    # DOMAIN CHECK
    if result["Type"] == "domain":
        whois_data = result.get("WHOIS", {})
        ip_info = result.get("IP Info", {})

        # Domain age
        creation_date = whois_data.get("Creation Date")
        if creation_date:
            if isinstance(creation_date, list):
                creation_date = creation_date[0]
            if isinstance(creation_date, str):
                creation_date = dateutil.parser.parse(creation_date)
            if creation_date.tzinfo is None:
                creation_date = creation_date.replace(tzinfo=timezone.utc)
            age_days = (datetime.now(timezone.utc) - creation_date).days
            if age_days < 180:
                findings.append("Domain < 6 bulan → suspicious")
            else:
                findings.append("Domain > 6 bulan → low risk")
        else:
            findings.append("Tanggal pembuatan domain tidak tersedia → suspicious")

        # WHOIS
        if "Error" in whois_data or not whois_data.get("Registrar"):
            findings.append("WHOIS private atau disembunyikan → suspicious")
        else:
            findings.append("WHOIS publik tersedia → low risk")

        # IP Country
        country = ip_info.get("Country")
        if country in HIGH_RISK_COUNTRIES:
            findings.append(f"IP berasal dari negara high-risk ({country}) → suspicious")
        elif country:
            findings.append(f"IP berasal dari negara {country} → informational")
        else:
            findings.append("Lokasi IP tidak teridentifikasi → suspicious")

    # USERNAME / EMAIL CHECK
    if "GitHub Info" in result:
        github = result["GitHub Info"]
        if "Error" in github:
            findings.append("Tidak ditemukan akun GitHub → suspicious")
        else:
            repo_count = len(github.get("Repositories", []))
            if repo_count == 0:
                findings.append("Akun GitHub tanpa repositori → suspicious")
            elif repo_count < 5:
                findings.append("Aktivitas GitHub minim → medium risk")
            else:
                findings.append("Aktivitas GitHub publik terdeteksi → low risk")

    if "Email Breach" in result:
        breach_info = result["Email Breach"]
        if "Error" in breach_info:
            findings.append("Error saat cek email breach → suspicious")
        elif breach_info.get("Breached"):
            findings.append(f"Email pernah bocor di breach: {', '.join(breach_info['Breaches'])} → high risk")
        else:
            findings.append("Email tidak pernah bocor → low risk")

    return findings

# =============================
# MAIN AGENT
# =============================
def osint_agent(input_str):
    input_type = detect_input_type(input_str)
    result = {"Input": input_str, "Type": input_type}

    if input_type == "domain":
        result["WHOIS"] = get_whois(input_str)
        result["IP Info"] = get_ip_info(input_str)
    elif input_type == "email":
        username = input_str.split("@")[0]
        result["GitHub Info"] = get_github_info_api(username)
        result["Email Breach"] = check_email_breach(input_str)
    else:  # username
        result["GitHub Info"] = get_github_info_api(input_str)

    return result

# =============================
# INTERACTIVE LOOP
# =============================
def run_osint_agent():
    while True:
        user_input = input("\nMasukkan domain / email / username (ketik 'exit' untuk keluar): ")
        if user_input.lower() == "exit":
            print("Keluar dari OSINT Agent")
            break

        result = osint_agent(user_input)
        findings = generate_findings(result)

        print("\n=== LAPORAN OSINT ===")
        print(f"Input  : {result['Input']}")
        print(f"Tipe   : {result['Type']}")
        print("\nTemuan / Findings:")
        for f in findings:
            print(f"- {f}")
        print("=" * 50)

# =============================
# RUN AGENT
# =============================
if __name__ == "__main__":
    run_osint_agent()